[build]
  command = "dotnet publish -c Release -o ./publish"
  publish = "publish"

[build.environment]
  DOTNET_VERSION = "8.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff" 